version: '3.4'

services:
  app-torchserve:
    image: pytorch/torchserve:latest-gpu
    ports:
      - 7070:7070
      - 7071:7071
      - 8080:8080
      - 8081:8081
      - 8082:8082
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./models:/tmp/models
      - ./logs:/home/model-server/logs
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count : 1
            capabilities: [gpu]
    command: ["torchserve", "--start", "--ncs", "--model-store", "/tmp/models", "--models", "all"]